backend = "glx";
vsync = true;
use-damage = true;
use-ewmh-active-win = true;
fading = true;
fade-in-step=0.06;
fade-out-step=0.06;
fade-delta = 5;
no-fading-openclose = false;

rules = (
	{
		match = "window_type = '' || "
		"window_type = 'tooltip' || "
		"window_type = 'dock' || "
		"window_type = 'dnd' || "
		"window_type = 'popup_menu' || "
		"window_type = 'dropdown_menu' || "
		"window_type = 'bar' || "
		"window_type = 'utility' || "
		"_NET_WM_STATE@[*] = '_NET_WM_STATE_HIDDEN' || "
	    "_NET_WM_STATE@[*] = '_NET_WM_STATE_MAXIMIZED_VERT' || "
		"_GTK_FRAME_EXTENTS@";
		corner-radius = 0;
		shadow = false;
		full-shadow = false;
	},
	{
		match = "! name = '' || "
		"class_g ?= 'chromium-browser' || "
		"class_g ?= 'picom'";
		corner-radius = 0;
		shadow = false;
		full-shadow=false;
		
	}
);
